# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               TrustKit
tagline:             Effortless and universal SSL pinning for iOS and OS X
url:                 https://datatheorem.github.io/TrustKit
paginate:            1
baseurl:             https://datatheorem.github.io/TrustKit

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              TrustKit Team
#  url:               https://twitter.com/mdo
#  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/datatheorem/TrustKit
